italiangrid/voms

src/api/ccapi/voms_api.h
src/server/vomsd-rest.cc
src/server/vomsd.cc
src/sslutils/sslutils.c

Regarding the gcc 6 failure, see:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811879

Various fixes

---

src/ac/init.c
src/sslutils/proxy.c
src/sslutils/proxycertinfo.c
src/sslutils/sslutils.c

This commit checks that all the calls to `OBJ_create` (directly or through the macro `OBJC`) are protected by a call to `OBJ_txt2nid` to see if the object already exists. The macro `OBJC` has been replaced by a proper function.

Fix issue #60

---

src/.gitignore
src/ac/extensions.c
src/ac/write.c

See [here](https://issues.infn.it/jira/browse/VOMS-875?focusedCommentId=89355&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-89355) for an explanation.
This PR (tentatively) addresses the incompatibility, but not yet the storm frontend segfault.

Fix AC incompatibilty introduced with the migration to OpenSSL 1.1

---

m4/acinclude.m4

This is not the most important change since the configure script now uses pkg-config and not AC_OPENSSL. I noticed this when I was compiling an older git snapshot that still used AC_OPENSSL, and I report it in case you would want to go back to use AC_OPENSSL sometime in the future.
In OpenSSL 1.1 CRYPTO_num_locks is a preprocessor macro defined in the openssl headers, and there no longer is a function with this name in the crypto library:
AC_CHECK_LIB only works with proper functions that exist in the library and fails if a preprocessor macro is used in the test.

Don't use macros in AC_CHECK_LIB

---

src/client/vomsclient.cc
src/utils/vomsfake.cc
testsuite/lib/vomslib.exp
testsuite/voms/voms/voms007.exp
testsuite/voms/voms/voms009.exp
testsuite/voms/voms/voms010.exp
testsuite/voms/voms/voms011.exp
testsuite/voms/voms/voms014.exp
testsuite/voms/voms/voms016.exp
testsuite/voms/voms/voms020.exp
testsuite/voms/voms/voms021.exp
testsuite/voms/voms/voms025.exp
testsuite/voms/voms/voms030.exp
testsuite/voms/voms/voms041.exp
testsuite/voms/voms/voms042.exp
testsuite/voms/voms/voms043.exp
testsuite/voms/voms/voms044.exp
testsuite/voms/voms/voms059.exp
testsuite/voms/voms/voms060.exp
testsuite/voms/voms/voms061.exp
testsuite/voms/voms/voms091.exp
testsuite/voms/voms/voms092.exp
testsuite/voms/voms/voms124.exp
testsuite/voms/voms/voms142.exp
testsuite/voms/voms/voms143.exp

The updated openssl 1.1.1 in Debian has new default security settings and rejects certificates with RSA key size less than 2048 bits by default. voms-proxy-init generates proxies with a key size of 1024 bits by default. Trying to connect using these proxies from a Debian machine with openssl 1.1.1 fails. See e.g. the Debian BTS bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911248.
This PR changes the default key size used by voms-proxy-init when generating proxies to 2048 bits.
The default key size used by grid-proxy-init has already been changed to 2048 bits (in both the old Globus Toolkit upstream and the new Grid Community Toolkit).

Change default proxy cert key length to 2048 bits

---

src/install/voms.start.in

If the RUN=yes assignment of the default value happens after the sourcing of the /etc/sysconfig configuration file, a RUN=no in the configuration file will be ignored.

Assign default value before reading sysconfig

---

configure.ac

This is a new version of #30 only against the develop-2.1.X branch. I'm closing #30.
Only test for gSOAP and WSDL2H when building server. This allows building the
non-server components on platforms without gSOAP.

GSOAP checks are only needed for server.

---

src/common/options.cc

~~~
options.cc: In function 'bool getopts(int, char* const*, option*)':
options.cc:201:18: warning: catching polymorphic type 'class std::bad_alloc' by\
value [-Wcatch-value=]
201 |   } catch ( std::bad_alloc) {
|                  ^~~~~~~~~
~~~

Catch exception by reference

---

src/sslutils/sslutils.c

Fixes use after free warning:
~~~
In function 'strcpy',
inlined from 'proxy_get_filenames' at sslutils.c:2707:23:
/usr/include/bits/string_fortified.h:79:10: warning: pointer may be used after 'free' [-Wuse-after-free]
~~~
Also fixes:
~~~
sslutils.c: In function 'ERR_load_prxyerr_strings': sslutils.c:459:41: warning: unused variable 'egd_path' [-Wunused-variable]
459 |     char *                              egd_path;
|                                         ^~~~~~~~
~~~

Use after free

---

src/api/ccapi/voms_apic.h

~~~
.../src/api/ccapi/voms_apic.h:207: warning: found documented return type for VOMS_DeleteContacts that does not return anything
~~~

Doxygen warning

---

src/sslutils/evaluate.c

~~~
evaluate.c: In function 'read_pathrestriction':
evaluate.c:356:5: warning: 'strncpy' output may be truncated copying 8 bytes from a string of length 8 [-Wstringop-truncation]
356 |     strncpy(signing + 1, hash, 8);
|     ^
evaluate.c:357:5: warning: 'strncpy' output may be truncated copying 8 bytes from a string of length 8 [-Wstringop-truncation]
357 |     strncpy(namespace + 1, hash, 8);
|     ^
~~~

May be truncated

---

src/api/ccapi/voms_api.h

voms_api.h is the public header included by code that uses the voms library. It must not include the config.h header which is internal to the voms build.

config.h must not be included in public header file

---

src/api/ccapi/api_util.cc

When verification of ACs fails, the prior behavior is to always have this message:
```
Cannot verify AC signature!
```
This can be difficult to debug as there's no indication of whether its a problem with the proxy itself or with the host configuration.
This patch appends the underlying error message if one was provided. For example,
```
Cannot verify AC signature!  Underlying error: Certificate verification \
failed for certificate '/CN=voms.example.com': certificate has expired.
```
(newlines added for readability)

If a detailed error message is available, do not overwrite

---

src/sslutils/lex.namespaces.c
src/sslutils/lex.signing.c
src/sslutils/lexparse.h
src/sslutils/namespaces.c
src/sslutils/namespaces.l
src/sslutils/namespaces.y
src/sslutils/signing_policy.c
src/sslutils/signing_policy.l
src/sslutils/signing_policy.y
src/utils/lex.yy.c
src/utils/lexparse.h
src/utils/vomsfake.y
src/utils/vomsparser.c
src/utils/vomsparser.l

And include them in a few strategic places.  This avoids build failures with future compilers that do not support implicit function declarations by default.
(NB: This commit does not regenerate the lexers/parsers, so the line numbers are slightly off.)
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

Add "lexparse.h" headers for lexer/parser integration

---

src/sslutils/proxy.c

This changes the processing of authority key identifier and subject key identifier extensions to only be done on certificates, not proxies.  This is an alternative fix to the problem identified in #113 (although the fix there turned out to also be needed for a different problem, certificates without an authority key identifier).

Only process authority & subject key identifiers in certs

---

src/sslutils/proxy.c

When using `voms-proxy-init` with a proxy certificate and OpenSSL 3 I get an error:
```bash
$ voms-proxy-init -out $PWD/test1
$ voms-proxy-init -cert $PWD/test1 -key $PWD/test1 -out $PWD/test2
Your proxy is valid until Tue Feb 14 00:52:34 2023
Error: verification failed.
Parameters unset!
```
If I use a `voms-proxy-init` binary that was compiled with OpenSSL 1.1.1 the above example works.
Looking deeper in to the problem I found that this line was failing with OpenSSL 3:
```c
ex11 = X509V3_EXT_conf_nid(NULL, &ctx, NID_authority_key_identifier, "keyid");
```
Inspecting the openssl error queue I found this message:
```
Error adding extension: error:1100007B:X509 V3 routines::unable to get issuer keyid
```
If I look at the certifictate that was generated with OpenSSL 1.1.1 I find the AKI is …

Only set authority key identified field if the public key is available

---

Makefile.am

Fixes build error if all targets are made.

Makefile: don't reference deleted INSTALL file in apidoc target

---

src/install/voms_install_db.in

voms-server: chown-with-dot root.voms [usr/share/voms/voms_install_db:276]
chown-with-dot
The named script uses a dot to separate owner and group in a call like
chown user.group but that usage is deprecated.
Please use a colon instead, as in:
chown user:group.

Fix lintian warning

---

src/server/vomsd.cc

The version of gsoap that comes with Rocky 9 does not call the request handlers in fparse.
The http_get handler never gets called on the server.
This causes clients to fail that use the REST API (voms-proxy-init3) as the server just terminates the connection without returning anything.
This is a quick patch that solves this by calling the http_get handler if fparse didn't.
This has only been tested on Rocky 9, but should also work on EL7/8 systems.

Fix problem with newer gsoap versions.

---

src/client/vomsclient.cc
src/common/data.cc
src/socklib/Server.cpp
src/sslutils/sslutils.c
testsuite/voms/voms/server.c
testsuite/voms/voms/server2.c

With OpenSSL 3, function names are not included any more in SSL errors; trying to print them is then meaningless.
This PR mainly changes how the error message obtained from the queue of SSL errors is produced, relying on the canonical loop over the queue and avoiding function names.
Partially addresses #110. More work is needed to correctly register VOMS-specific errors, which doesn't seem quite right even in the current implementation.

Avoid function names when printing OpenSSL errors
